### ISSUE TITLE
Support for custom cucumber environments

### ISSUE THREAD

**Issue by tomlauwyck** [jonleighton/spring-commands-cucumber#2]
Hi,

I might be missing something here, but I'm under the impression that the bin/cucumber command will always run in the test environment. At work we use different environments for rspec and cucumber since that enables us to run the specs and cukes alongside without them hitting the same database. 
I monkey patched my way out of the problem by overriding the env method in Spring::Commands::Cucumber and having it return the string I need. 
I would have expected to be able to pass a RAILS_ENV='foo' to the command, since that seems to be the convention if one needs to override the default rails env.
Any chance of that being implemented in the future? 

Thanks in advance

**Comment by maxschulze** [comment]
@tomlauwyck Can you check my pull request #4 to see if RAILS_ENV works for you?
