### ISSUE TITLE
No such file or directory - cucumber

### ISSUE THREAD

**Issue by lorin** [jonleighton/spring-commands-cucumber#3]
I'm running a Rails 4 app, configured with Spring. I installed spring-commands-cucumber 1.0.1 and did: `spring binstub --all`. When I run `bin/cucumber`, I get the following error message:

```
Version: 1.1.2

Usage: spring COMMAND [ARGS]

Commands for spring itself:

  binstub         Generate spring based binstubs. Use --all to generate a binstub for all known commands.
  help            Print available commands.
  status          Show current status.
  stop            Stop all spring processes for this project.

Commands for your application:

  cucumber        Runs the cucumber command
  rails           Run a rails command. The following sub commands will use spring: console, runner, generate, destroy.
  rake            Runs the rake command
  rspec           Runs the rspec command
No such file or directory - cucumber. Please create a cucumber directory to get started. (Errno::ENOENT)
```

I thought feature files go in the "features" directory, not the cucumber directory.

**Comment by maxschulze** [comment]
Doesn't work for me either.

**Comment by maxschulze** [comment]
Reverting to spring 1.0.0 works, but then cucumber doesn't seem to run in RAILS_ENV=test

**Comment by maxschulze** [comment]
@lorin Can you check if my pull #4 fixes it for you?

**Comment by lorin** [comment]
@maxschulze Yes, your pull request appears to resolve the issue for me. I installed it by doing:

```
group :development do
    gem 'spring-commands-cucumber', github: 'maxschulze/spring-commands-cucumber', branch: 'master'
end
```

**Comment by maxschulze** [comment]
@lorin Thanks for the Feedback. @jonleighton was so kind to merge it to master, so it should be fixed in the next gem version.

Thanks for your fast response.

**Comment by replaid** [comment]
I am having this exact issue with a brand new Rails 4.1.1 app and spring-commands-cucumber 1.1.0. Please let me know if it would be of value to create a repository reproducing this issue.
